version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: "${DB_NAME}"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${DB_USER_NAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DB_USER_PASSWORD}"
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - db_data:/data/db
      - db_archive:/Databases/dev.archive
      - db_production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: "${DB_NAME}_express"
    environment:
      - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER_NAME}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_USER_PASSWORD}"
      - "ME_CONFIG_MONGODB_URL=mongodb://${DB_USER_NAME}:${DB_USER_PASSWORD}@mongo:27017/?authSource=admin"
      - "ME_CONFIG_BASICAUTH_USERNAME=${DB_USER_NAME}"
      - "ME_CONFIG_BASICAUTH_PASSWORD=${DB_USER_PASSWORD}"
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
volumes:
  db_data:
  db_archive:
  db_production:
